dist: trusty
group: edge
language: java
sudo: required
jdk: openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - cd sandwich-shop-manager
  - mvn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report